### ISSUE TITLE
Add convenience methods for executing queries and calls under default connection

### ISSUE THREAD

**Issue by vosolovskiy** [ftldb/ftldb#19]
The usage of `default_connection().query(...)` and `default_connection().exec(...)` looks verbose.

Add convenience methods `query(...)` and `exec(...)`, which can be invoked without specifying a connection. In this case the default connection is used (either kprb or a manually set external connection).

**Comment by sns777** [comment]
I doubting that this is a necessary complement - looks clumsy. May be add these into `sql_ftl` package as functions?

**Comment by vosolovskiy** [comment]
I've received a complaint about the verbosity of these most frequently used methods. Working in Oracle environment users don't want to specify the connection every time.

@sns777 Maybe you're right. It looks more reasonable to include them in the `sql_ftl` macro lib.
Pros: there's no need to "breed" Java code.
Cons: users must import the lib, though they're very likely to do it anyway.

**Comment by sns777** [comment]
My opinion is when user want to use sql inside ftl, he must import the sql_ftl.

But, the one question - why the routine that execute a callable statement has name `exec`, when it seems that the corrent name is `call`.

**Comment by vosolovskiy** [comment]
Fixed.

**Comment by sns777** [comment]
reviewed: ok
