### ISSUE TITLE
v1.5.0 roadmap

### ISSUE THREAD

**Issue by vosolovskiy** [ftldb/ftldb#23]
The main goals of v1.5.0 are:

1. Make templates portable and independent of the processing side: Oracle or client.
2. Adapt Oracle code to easy import/work with templates originally written for the client-side with no extra effort.
3. Integrate FTLDB with the upcoming plugin for SQL Developer.

The high-level changes regarding these goals are:

1. Consider client-side templates as Java resources. Use a new template loader for them instead of original FileTemplateLoader, which has some limitations.
2. Make it possible in Oracle to load templates from JAVA RESOURCE objects.
3. Introduce a new name format for client-side templates, which can be used on both sides.
4. Create a new API for the plugin.

**Comment by MikeKutz** [comment]
I've already written something to pull templates from various sources.  But, it is in pure PL/SQL
The goal was to incorporate that API in the DAL.

Let me know what you think.
https://github.com/MikeKutz/oddgen-templates

MK
