### ISSUE TITLE
install under git msys require move 'ftl java plsql resources' to scripts folder

### ISSUE THREAD

**Issue by bysov-r** [ftldb/ftldb#4]
user@host /c/user/lib/ftldb/tags/v1.2.1/src/main/scripts
$ usr_install.sh tns user pwd
-------------------------------------------
------------ INSTALLING FTLDB -------------
-------------------------------------------

Log file: setup/!usr_install_nrs_dev_prod_upd.log

Run SQL*Plus installation script.

SQL*Plus: Release 11.2.0.1.0 Production on Вт Мар 31 17:11:06 2015

Copyright (c) 1982, 2010, Oracle.  All rights reserved.

Присоединен к:
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
With the Partitioning option

SQL*Plus script started.
Switch to USER schema.

Сеанс изменен.

Create NUMBER_NT type.
Не удается найти указанный файл.
Отсоединено

**Comment by vosolovskiy** [comment]
If you're a Windows user, don't use shell scripts under Cygwin or other shell-emulators. Loadjava in Oracle Client for Win is a batch script and won't work!

Use only usr_install.bat.

**Comment by vosolovskiy** [comment]
Moreover, according to this:
> SQL*Plus: Release 11.2.0.1.0 Production on Вт Мар 31 17:11:06 2015

it seems you have Oracle Client 11.2.0.1.0 for Windows installed. It has a buggy `loadjava` utility. Update your client, if you have problems with loading jars into DB.
