### ISSUE TITLE
install demo requires synonyms install (notice is absent)

### ISSUE THREAD

**Issue by bysov-r** [ftldb/ftldb#5]
user@host /c/usr/lib/ftldb/tags/v1.2.1/src/demo/plsql/usage_comparison
$ sp dev #custom script to run sqlplus 
SQL*Plus: Release 11.2.0.1.0 Production on Tue Mar 31 17:49:33 2015

Copyright (c) 1982, 2010, Oracle.  All rights reserved.

Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
With the Partitioning option

SQL> @!install
Create SHOPS table.

Table created.

Create GENERATOR package.

Warning: Package created with compilation errors.

Warning: Package Body created with compilation errors.

Generate ORDERS table.
  generator.gen_orders_plsql();
  *
ERROR at line 3:
ORA-06550: line 3, column 3:
PLS-00905: object USER.GENERATOR is invalid
ORA-06550: line 3, column 3:
PL/SQL: Statement ignored

**Comment by vosolovskiy** [comment]
Please read the Installation section in `README.md`.
You musn't use the project source directory to install FTLDB or demo (actually you cannot).

Download the installer archive (or build it yourself using Maven) and run scripts from there.
