### ISSUE TITLE
Problems with installing FTLDB, pt. 5

### ISSUE THREAD

**Issue by bysov-r** [ftldb/ftldb#7]
ORA-20000: FTLDB initialization failed
ORA-06512: на  "USER.FTLDB_API", line 114
ORA-29540: класс ftldb/Configurator не существует
ORA-06512: на  "USER.GENERATOR", line 100
ORA-06512: на  line 6

CALL dbms_java.grant_permission ('USER', 'SYS:java.lang.RuntimePermission', 'getClassLoader', '' )
select ENABLED from dba_java_policy WHERE grantee = 'USER' AND NAME = 'getClassLoader' -- ENABLED

c:\user\lib\ftldb\tags\v1.2.1\src\main\scripts>loadjava.bat -u user/pwd@host:1521:sid -resolve -grant public -verbose -stdout java\freemarker\core\EnvironmentInternalsAccessor.java  -thin
creating : source freemarker/core/EnvironmentInternalsAccessor
loading  : source freemarker/core/EnvironmentInternalsAccessor
granting : execute on source freemarker/core/EnvironmentInternalsAccessor to public
granting : execute on class freemarker/core/EnvironmentInternalsAccessor to public
resolving: source freemarker/core/EnvironmentInternalsAccessor
errors   : source freemarker/core/EnvironmentInternalsAccessor
    ORA-29535: источник требует перекомпиляции
    freemarker/core/EnvironmentInternalsAccessor:19: cannot find symbol
    symbol  : class Template
    location: package freemarker.template
    import freemarker.template.Template;

**Comment by vosolovskiy** [comment]
Have you installed FTLDB properly? Have both freemarker.jar and ftldb.jar been loaded?

Please copy the content of `setup/*.log` files here.

**Comment by bysov-r** [comment]
you havn't noticed about loadjava.bat use.
freemarker.jar is absent.
it seems like pure set of freemarker sources.

**Comment by vosolovskiy** [comment]
Have you read README?
It is mentioned that:

 1. You need Oracle Client (with loadjava).
 2. You musn't use v11.2.0.1.0 on Windows due to a bug.
 3. You should unpack the release archive and find all the described folders and files in the target directory.

If you have downloaded and unpack the release installation archive, you can find freemarker.jar in the `java` directory.

Run the installer as described. If you have problems please attach the log file.

**Comment by vosolovskiy** [comment]
> c:\user\lib\ftldb\tags\v1.2.1\src\main\scripts>loadjava.bat -u user/pwd@host:1521:sid -resolve -grant public -verbose -stdout java\freemarker\core\EnvironmentInternalsAccessor.java -thin

You're ignoring my advice to download the installer archive https://github.com/ftldb/ftldb/releases/download/v1.2.1/ftldb-1.2.1-install-win.zip and use it for installation.
Instead you keep working with the sources. You NEEDN'T use `loadjava` explicitly. It is called by the installer. You CANNOT install the product from the sources.

If you want to use sources read the `Building the project` section.

> З.Ы. инсталляция пока похожа на конструктор - "разведай сам"
> есть пожелание сделать "sample workaround" где шаг за шагом можно выйти на рабочий результат из demo. с проверками необходимых условий (что требуется для корректной отработки скриптов). в текущем состоянии многовато тепличных условий для запуска на "попробовать")

Here's the short manual:

1. Download [this file](https://github.com/ftldb/ftldb/releases/download/v1.2.1/ftldb-1.2.1-install-win.zip).
2. Unpack it.
3. Change directory to `ftldb-1.2.1`.
4. Run from this directory:
`dba_install.bat <dbname> sys <syspswd> ftldb ftldb`
5. It must complete with the `INSTALLATION COMPLETED SUCCESSFULLY` message.
6. Download [another file](https://github.com/ftldb/ftldb/releases/download/v1.2.0/ftldb-1.2.0-demo-win.zip).
7. Unpack it.
8. Change directory to `ftldb-1.2.1-demo`.
9. Run from this directory:
`install.bat <dbname> sys <syspswd> ftldb ftldemo ftldemo`
10. It must complete with the `INSTALLATION COMPLETED SUCCESSFULLY` message.
11. Connect as `ftldemo/ftldemo` and explore the objects.
12. Now you may run the demo scripts.

**Comment by bysov-r** [comment]
thnx
