### ISSUE TITLE
Add API methods for getting FTLDB version.

### ISSUE THREAD

**Issue by vosolovskiy** [ftldb/ftldb#9]
Add methods to Java and PL/SQL for getting FTLDB version:

1. as a string in X.Y.Z format;
2. as a comparable integer.

The version must be set from the ${project.version} POM attribute during the project assemblying.

**Comment by sns777** [comment]
Not sure about comparable integer. May be as comparable string containing three integers with leading zeros delimited by dots?

**Comment by sns777** [comment]
I.e. stiring with any previous version must be less than string with current version.
